name = "pki-bitbstrd"
type = "webpack"
account_id = "149fc59d5c2cf07d4c56c4b5bbac5cbd"
workers_dev = true
route = "pki.bitbstrd.com/*"
zone_id = "60b2ab47a3fd3092aaf2f5d5ffb0881d"

[site]
bucket = "./public"

[env.dev]
workers_dev = true